name: Smoke tests

on:
  workflow_dispatch:

jobs:
  sierraLeone:
    if: github.repository_owner == 'PIH'
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/execute-pihemr-smoke-tests.yml@main
    with:
      image_name: partnersinhealth/pihsl-emr
      pih_config: sierraLeone
      suite: sierraleone
      admin_user_password: 'd@t45Aves!'
    secrets: inherit
