name=${project.name}
version=${project.version}

parent.groupId=${parentGroup}
parent.artifactId=${parentArtifact}
parent.version=${parentVersion}
parent.type=jar

content.${parentContentArtifactId}=${parentContentVersion}
content.${parentContentArtifactId}.groupId=${parentContentGroupId}
content.${parentContentArtifactId}.namespace=

content.${contentArtifact}=${contentVersion}
content.${contentArtifact}.groupId=${contentGroup}
content.${contentArtifact}.namespace=

spa.artifactId=${frontendArtifact}
spa.groupId=${frontendGroup}
spa.version=${frontendVersion}
spa.includes=${frontendArtifact}-${frontendVersion}

property.pih.config.prompt=Specify PIH config (sierraLeone,sierraLeone-kgh | sierraLeone,sierraLeone-wellbody | sierraLeone,sierraLeone-kgh,sierraLeone-kgh-test | sierraLeone,sierraLeone-wellbody,sierraLeone-wellbody-gladi)?
property.pih.config.default=sierraLeone,sierraLeone-kgh,sierraLeone-kgh-test
